Feature-Bright:send-assessment-email-api
world-wide-techies/talentyard pull request #13
Opened 2023-09-08 19:47 UTC by Brightlaz

Created the api and followed all the instructions

2023-09-09 08:53 UTC, edidee approved these changes

2023-09-11 01:32 UTC, annonymousauthority requested changes
Please remove the comments

2023-09-11 01:33 UTC, annonymousauthority commented on Developers/app/api/sendAssessmentEmail/route.js
> +      service: process.env.EMAIL_SERVICE_PROVIDER, // e.g., 'Gmail', 'Yahoo', etc.
You're going to need 
`NEXT_PUBLIC_[NAME_OF_VARIABLE]` for Next.js environment variable

2023-09-11 01:38 UTC, annonymousauthority requested changes
I'll like to believe this code wasn't copied from somewhere, which obviously it was.

Just work on the points mentioned.

2023-09-11 01:38 UTC, annonymousauthority commented on Developers/app/api/sendAssessmentEmail/route.js
> +export async function POST() {
It requires a parameter requests

2023-09-11 01:38 UTC, annonymousauthority commented on Developers/app/api/sendAssessmentEmail/route.js
> +    const { to, subject, html } = NextRequest.body;
I'll recommend more of the `await request.json()` request being the parameter argument which will be the body.

2023-09-11 01:38 UTC, annonymousauthority commented on Developers/app/api/sendAssessmentEmail/route.js
> +      from: "your-email@example.com",
This should be an environment variable called
`NEXT_PUBLIC_SENDER_EMAIL`

2023-09-11 01:38 UTC, annonymousauthority commented on Developers/app/api/sendAssessmentEmail/route.js
> +    console.error("Error sending email:", error);
CONSOLE.error can be removed

2023-09-11 01:46 UTC, Brightlaz commented on Developers/app/api/sendAssessmentEmail/route.js
> +      service: process.env.EMAIL_SERVICE_PROVIDER, // e.g., 'Gmail', 'Yahoo', etc.
Just checking the Next documentation now which confirms i called the environment variable the right way sir, 
Or if it not what you were referring to please direct me to the particular section

2023-09-11 08:12 UTC, annonymousauthority requested changes
Ok this works, just write a function that handles handlebar template configuration not inline.

2023-09-11 08:12 UTC, annonymousauthority requested changes
Ok this works, just write a function that handles handlebar template configuration not inline.

2023-09-14 11:08 UTC, annonymousauthority requested changes
Not configured for handlebars template

2023-09-14 16:59 UTC, annonymousauthority approved these changes
LG

2023-09-14 16:59 UTC, merged