Feature joseph welcome email
world-wide-techies/talentyard pull request #16
Opened 2023-09-08 23:00 UTC by Olayanju-1234

feature-Joseph-welcome-email

2023-09-09 10:40 UTC, Remi-dee approved these changes
Seen

2023-09-11 01:52 UTC, annonymousauthority commented on Developers/app/api/welcomeEmail/route.js
> +    const transporter = nodemailer.createTransport({
We'll be using 
`NEXT_PUBLIC_[ENVIRONMENT VARIABLE NAME]`

Let's also stay consistent with the EV naming, so communicate with other developers working with same Variables.

2023-09-11 01:53 UTC, annonymousauthority commented on Developers/app/api/welcomeEmail/route.js
> +    const mailData = {
We'll be using a handlebar template.
This configuration doesn't work for that. Can you change this?

If you're having difficulty, you can reach out.

2023-09-11 01:53 UTC, annonymousauthority requested changes
Pretty basic.
Doesn't feel like much thought was put into it.

let's fix this!

2023-09-11 21:28 UTC, Olayanju-1234 commented on Developers/app/api/welcomeEmail/route.js
> +    const transporter = nodemailer.createTransport({
I have made corrections to the environment variables naming. They all follow the required pattern now.

2023-09-11 21:29 UTC, Olayanju-1234 commented on Developers/app/api/welcomeEmail/route.js
> +    const mailData = {
I made my handlebar file and linked it to the code in my local environment. I created an EV for the path of the template that might be added later.

2023-09-11 21:32 UTC, closed without merging