Component-Bright:Sign-In-Component
world-wide-techies/talentyard pull request #39
Opened 2023-09-23 00:33 UTC by Brightlaz

![signIn](https://github.com/world-wide-techies/talentyard/assets/97971556/a8fbc35b-cc88-4704-8739-d416965b83f9)
The storybook build has crashed, i'll check it out tomorrow

2023-09-23 15:23 UTC, annonymousauthority requested changes
Please show a visual of your work.

2023-09-23 15:25 UTC, Brightlaz commented
> Please show a visual of your work.

I added a visual above ☝️

2023-09-23 15:35 UTC, Remi-dee commented on Developers/app/components/onboardTechies/SignInForm.js
> +import { Lexend } from "next/font/google";
You don't need this import

2023-09-23 15:37 UTC, Remi-dee requested changes

2023-09-23 15:37 UTC, Remi-dee commented on Developers/app/components/onboardTechies/SignInForm.js
> +const lexend = Lexend({
This font has been configured at top level, you now have access to it without initializing it again

2023-09-26 11:14 UTC, annonymousauthority requested changes
Changes required

2023-09-26 11:14 UTC, annonymousauthority commented on Developers/app/components/onboardTechies/SignInForm.js
> +    <div className="w-full max-w-xs sm:max-w-[608px] mx-auto mt-10 space-y-[33px]">
Please remove all classes from this div, keep `space-y-6` rather than `33px`

2023-09-26 11:14 UTC, annonymousauthority commented on Developers/app/components/onboardTechies/SignInForm.js
> +      <form onSubmit={handleSignIn} className="space-y-[31px]">
Let's use a form object for the value of each input rather than individual values.

2023-09-26 11:14 UTC, annonymousauthority commented on Developers/app/components/onboardTechies/SignInForm.js
> +            <p
An onclick shouldn't be given to a paragraph element, you can use a `Next/Link` for this

2023-09-26 11:14 UTC, annonymousauthority commented on Developers/app/components/onboardTechies/SignInForm.js
> +            className="w-full max-w-[227px] py-3 bg-primary rounded-xl hover:shadow-lg shadow-accentSecondary/30 transition delay-150 ease-in-out hover:scale-105 duration-300 hover:bg-dark text-white
primary buttons use `bg-dark` on hover not accent

2023-09-26 11:14 UTC, annonymousauthority commented on Developers/app/components/onboardTechies/SignInForm.js
> +            className="w-full max-w-[227px] py-3 bg-primary rounded-xl hover:shadow-lg shadow-accentSecondary/30 transition delay-150 ease-in-out hover:scale-105 duration-300 hover:bg-dark text-white
Don't forget to change the text color too

2023-09-26 12:16 UTC, Brightlaz commented on Developers/app/components/onboardTechies/SignInForm.js
> +            className="w-full max-w-[227px] py-3 bg-primary rounded-xl hover:shadow-lg shadow-accentSecondary/30 transition delay-150 ease-in-out hover:scale-105 duration-300 hover:bg-dark text-white
@annonymousauthority This part of the review is not clear as i used bg-dark on hover already so i don't know which other hover again and also wat text color I'm i changing??

2023-09-26 18:26 UTC, annonymousauthority commented on Developers/app/components/onboardTechies/SignInForm.js
> +            className="w-full max-w-[227px] py-3 bg-primary rounded-xl hover:shadow-lg shadow-accentSecondary/30 transition delay-150 ease-in-out hover:scale-105 duration-300 hover:bg-dark text-white
You can mark this as resolved4

2023-09-26 18:28 UTC, annonymousauthority requested changes
Please attend to the comments and mark as resolved for where you believe has already been handled

2023-09-26 18:28 UTC, annonymousauthority commented on Developers/app/components/onboardTechies/SignInForm.js
> +            className="w-full max-w-[227px] py-3 bg-primary rounded-xl hover:shadow-lg shadow-accentSecondary/30 transition delay-150 ease-in-out hover:scale-105 duration-300 hover:bg-dark text-white
Please make the max-width only for large screens, and allow the button fill the screen for mobiles

2023-09-26 18:28 UTC, annonymousauthority commented on Developers/app/components/onboardTechies/SignInForm.js
> +            className="w-full max-w-[227px] py-3 bg-primary rounded-xl hover:shadow-lg shadow-accentSecondary/30 transition delay-150 ease-in-out hover:scale-105 duration-300 hover:bg-dark text-white
Please also remove the shadow used for this button, doesn't look right.

2023-09-27 07:42 UTC, annonymousauthority approved these changes
Seen

2023-09-27 07:43 UTC, merged