Component-Aaron: Referral
world-wide-techies/talentyard pull request #42
Opened 2023-09-24 09:31 UTC by twikista

Added 
![Referral component GIF](https://github.com/world-wide-techies/talentyard/assets/35855719/36c5ecca-4e93-4857-9fdd-5c7a0a207d6b)
Referral component

2023-09-24 15:42 UTC, twikista commented
Refactored referral component into a client side component since it has click interactions

2023-09-25 07:34 UTC, annonymousauthority requested changes
Reduce font weight of the text as shown in the design

2023-09-25 07:34 UTC, annonymousauthority commented on Developers/app/components/Referral_comp.js
> +    <div className='p-4 md:p-8 border border-solid space-y-5 md:space-y-9 rounded-3xl border-secondary w-full max-w-[950px] bg-white shadow-[0px_4px_4px_0px_rgba(77,144,219,0.21)] text-black text-bas
width not required

2023-09-25 07:34 UTC, annonymousauthority commented on Developers/app/components/Referral_comp.js
> +        <p>
Fonts thicker than it is in design

2023-09-25 07:34 UTC, annonymousauthority commented on Developers/app/components/Referral_comp.js
> +      <div className='flex flex-col items-center justify-between space-x-1 text-base font-medium text-black md:flex-row md:text-lg lg:text-xl'>
1. Equal space between referral link and link not in design.
2. Hovering on URL gives and underline.
3. On mobile the format of texts is `Referral link`, link below aligned to the left and copy by the side of link. making sure the link is truncated if passing a certain width. Referr to design if confused

2023-09-25 13:16 UTC, twikista commented on Developers/app/components/Referral_comp.js
> +    <div className='p-4 md:p-8 border border-solid space-y-5 md:space-y-9 rounded-3xl border-secondary w-full max-w-[950px] bg-white shadow-[0px_4px_4px_0px_rgba(77,144,219,0.21)] text-black text-bas
width removed

2023-09-25 13:17 UTC, twikista commented on Developers/app/components/Referral_comp.js
> +      <div className='flex flex-col items-center justify-between space-x-1 text-base font-medium text-black md:flex-row md:text-lg lg:text-xl'>
component refactored to meet design specifications

2023-09-25 13:25 UTC, twikista commented
@annonymousauthority 
The screen recorder makes the font looks bold. Also, the difference between the design and the implementation may be due to the difference in font family used in the design (Inter) and code implementation (Lexend). please see screenshots

![chrome-capture-2023-8-25 (2)](https://github.com/world-wide-techies/talentyard/assets/35855719/0e99a3b9-77b9-4e09-935e-6d267bc29e39)
![download](https://github.com/world-wide-techies/talentyard/assets/35855719/fb180b9b-8c91-4492-a19a-9468786b6976)
![download (1)](https://github.com/world-wide-techies/talentyard/assets/35855719/2898b2cd-a6b9-4f25-9ebb-a6a99f7f4bf4)

2023-09-27 08:47 UTC, annonymousauthority approved these changes
Seen

2023-09-27 08:47 UTC, merged