added welcome email template
world-wide-techies/talentyard pull request #8
Opened 2023-09-08 13:18 UTC by twikista

added welcome email template

2023-09-08 17:26 UTC, Remi-dee commented on app/api/Templates/welcomeEmailTemplate.handlebars
> +     {{!-- code below ensurs that PNG images display at the right size in Outlook
You can take out the comments, might not be necessary.

2023-09-08 17:28 UTC, Remi-dee requested changes

2023-09-08 17:28 UTC, Remi-dee commented on app/api/Templates/welcomeEmailTemplate.handlebars
> +      {{!-- profile action --}}
Here as well

2023-09-08 19:01 UTC, twikista commented
comments removed

2023-09-08 19:03 UTC, annonymousauthority requested changes
Codes shouldn't be commented and sent to the PR

2023-09-09 13:12 UTC, twikista commented
> Codes shouldn't be commented and sent to the PR

All comments removed from code

2023-09-11 01:56 UTC, annonymousauthority requested changes
Use the corrections on the other PR to fix the concerns in this one as well

2023-09-11 17:44 UTC, twikista commented
> Use the corrections on the other PR to fix the concerns in this one as well

corrections implemeted
@annonymousauthority

2023-09-11 19:26 UTC, annonymousauthority approved these changes
LG

2023-09-11 19:27 UTC, merged